CREATE TABLE IF NOT EXISTS sismed.errors
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    messa varchar null,
    rownumber bigint,
    file_id integer,
    CONSTRAINT errors_pk PRIMARY KEY (id)
);

CREATE INDEX errors_file_id_idx
    ON sismed.errors USING btree
    (file_id ASC NULLS LAST)
    TABLESPACE pg_default;