-- -----------------------------------------------------
-- Table user
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS sismed."actor" (
	id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(255) NULL,
	info varchar(255) NULL,
	status bool NOT NULL,
	CONSTRAINT actor_pk PRIMARY KEY (id)
);

-- -----------------------------------------------------
-- Data for actor
-- -----------------------------------------------------
INSERT INTO sismed.actor(
	name, info, status)
	VALUES ('01', 'Actor que elabora o importa el medicamento a reportar', true);

INSERT INTO sismed.actor(
	name, info, status)
	VALUES ('02', 'Actor que no elabora ni importa el medicamento', true);

