-- -----------------------------------------------------
-- Table user
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS sismed."log_report" (
	id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	initial_date date NOT NULL,
	finish_date date NOT NULL,
	file_type integer NOT null,
	status bool NOT NULL,
	CONSTRAINT log_report_pk PRIMARY KEY (id)
);
