-- -----------------------------------------------------
-- Table document_type
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS sismed."document_type" (
	id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name varchar(255) NULL,
	info varchar(255) NULL,
	status bool NOT NULL,
	CONSTRAINT document_type_pk PRIMARY KEY (id)
);


-- -----------------------------------------------------
-- Data for document_type
-- -----------------------------------------------------
INSERT INTO sismed.document_type(
	name, info, status)
	VALUES ('NI', 'NIT', true);
	
INSERT INTO sismed.document_type(
	name, info, status)
	VALUES ('MU', 'Municipio', true);
	
INSERT INTO sismed.document_type(
	name, info, status)
	VALUES ('DE', 'Departamento', true);
	
INSERT INTO sismed.document_type(
	name, info, status)
	VALUES ('DI', 'Distrito', true);