-- -----------------------------------------------------
-- Table medicine
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS sismed.medicine (
    id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    consecutive int4 NOT NULL,
	description varchar(255) NULL,
	expedient int4 NOT NULL,
	status bool NOT NULL,
	CONSTRAINT medicine_pkey PRIMARY KEY (id));