CREATE TABLE IF NOT EXISTS sismed.transaction_type
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default",
    info character varying(255) COLLATE pg_catalog."default",
    status boolean NOT NULL,
    CONSTRAINT transaction_type_pk PRIMARY KEY (id)
);

CREATE INDEX transaction_type_idx
    ON sismed.transaction_type USING btree
    (name COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;


INSERT INTO sismed.transaction_type(
	name, info, status)
	VALUES ('01', 'Transacción primaria institucional', true);

INSERT INTO sismed.transaction_type(
	name, info, status)
	VALUES ('02', 'Transacción primaria comercial', true);

INSERT INTO sismed.transaction_type(
	name, info, status)
	VALUES ('03', 'Transacción secundaria institucional', true);

INSERT INTO sismed.transaction_type(
	name, info, status)
	VALUES ('04', 'Transacción secundaria comercial', true);

INSERT INTO sismed.transaction_type(
	name, info, status)
	VALUES ('05', 'Transacción final institucional', true);