-- -----------------------------------------------------
-- Table user
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS sismed."user" (
	id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	first_name varchar NOT NULL,
	last_name varchar NOT NULL,
	email varchar NOT NULL,
	"password" varchar NOT NULL,
	create_time timestamp(0) NOT NULL,
	update_time timestamp(0) NULL,
	document_type_id int NOT NULL,
    actor_id int NOT NULL,
    avaliability_code varchar   NULL,
	CONSTRAINT user_pk PRIMARY KEY (id),
	CONSTRAINT document_type_FK FOREIGN KEY (document_type_id) REFERENCES sismed.document_type (id),
    CONSTRAINT actor_FK FOREIGN KEY (actor_id) REFERENCES sismed.actor (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS user_email_idx ON sismed."user" (email);

INSERT INTO sismed."user"
(first_name, last_name, email, "password", create_time, update_time, document_type_id, actor_id, avaliability_code)
VALUES('Administrador', 'Hospital', 'admin@dominio.com', '$2a$10$LqbGeQqVtOAFSQN0gcsuTuKlerFrWwibDjN5yA9EU3Dn6lAgpMm8W', '2021-06-03', '2021-06-03', 1, 1, '1234567891');
