-- -----------------------------------------------------
-- Table sismed_file
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS sismed.sismed_file (
    id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    end_date date NULL,
	file_name varchar(255) NULL,
	identification varchar(255) NULL,
	identification_type varchar(255) NULL,
	register_type int NULL,
	start_date date NULL,
	total_medications int NULL,
	total_records int NULL,
	CONSTRAINT sismed_file_pkey PRIMARY KEY (id));