-- -----------------------------------------------------
-- Table user_role
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS sismed.user_role (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  user_id int NOT NULL,
  role_id int NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT user_id_FK FOREIGN KEY (user_id) REFERENCES sismed.user (id),
  CONSTRAINT role_id_FK FOREIGN KEY (role_id) REFERENCES sismed.role (id));

INSERT INTO sismed.user_role
(user_id, role_id)
VALUES(1, 1);