-- -----------------------------------------------------
-- Table role
-- -----------------------------------------------------
 CREATE TABLE IF NOT EXISTS  sismed.role (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name varchar NOT NULL,
  description varchar NOT NULL,
  create_time timestamp(0) NOT NULL,
  update_time timestamp(0),
  CONSTRAINT role_pk PRIMARY KEY (id));

-- -----------------------------------------------------
-- Data for role
-- -----------------------------------------------------
INSERT INTO sismed.role (name, description, create_time) VALUES ('ROLE_ADMIN', 'Administrative user', Current_timestamp);
INSERT INTO sismed.role (name, description, create_time) VALUES ('ROLE_USER', 'Standard user', Current_timestamp);