-- -----------------------------------------------------
-- Table detail_imported_file
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS sismed.detail_imported_file (
    id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    amount float8 NULL,
    consecutive int4 NULL,
    expedient varchar(255) NULL,
    first_ium varchar(255) NULL,
    invoice_date date NULL,
    invoice_number varchar(255) NULL,
    nit varchar(255) NULL,
    second_ium varchar(255) NULL,
    third_ium varchar(255) NULL,
    transaction_type varchar(255) NULL,
    unit_invoice varchar(255) NULL,
    unit_value float8 NULL,
    imported_file_id int NOT NULL,
    invoice_month int NULL,
    line bigint NULL,
    CONSTRAINT detail_imported_file_pkey PRIMARY KEY (id),
    CONSTRAINT detail_imported_file_imported_file_FK FOREIGN KEY (imported_file_id) 
        REFERENCES sismed.imported_file (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
        );

CREATE INDEX detail_imported_file_transaction_type_idx
    ON sismed.detail_imported_file USING btree
    (transaction_type COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE INDEX detail_imported_file_unit_invoice_idx
    ON sismed.detail_imported_file USING btree
    (unit_invoice COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;