-- -----------------------------------------------------
-- Table unit_invoice
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS sismed.unit_invoice (
    id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    description varchar(255) NULL,
	status bool NOT NULL,
	info varchar(255) NULL,
	CONSTRAINT unit_invoice_pkey PRIMARY KEY (id));

CREATE INDEX unit_invoice_idx
    ON sismed.unit_invoice USING btree
    (description COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

-----------------------------------------------------
-- Data for Table unit_invoice
-----------------------------------------------------
INSERT INTO sismed.unit_invoice(
	description, status, info)
	VALUES ('A', true, 'Presentacion comercial');
	
INSERT INTO sismed.unit_invoice(
	description, status, info)
	VALUES ('B', true, 'Unidad por embalaje primario');
	
INSERT INTO sismed.unit_invoice(
	description, status, info)
	VALUES ('C', true, 'Unidad de dispensación');
	
INSERT INTO sismed.unit_invoice(
	description, status, info)
	VALUES ('D', true, 'Unidad mínima de concentración');